//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bioweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida
    {
        public int id_salida { get; set; }
        public int usuario_sistema { get; set; }
        public int producto { get; set; }
        public int responsable { get; set; }
        public int cliente { get; set; }
        public int conductor { get; set; }
        public string numero_placa { get; set; }
        public string consecutivo { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public Nullable<decimal> caneca { get; set; }
        public Nullable<decimal> galon { get; set; }
        public Nullable<decimal> peso_bruto { get; set; }
        public Nullable<decimal> tara { get; set; }
        public Nullable<decimal> peso_neto { get; set; }
        public Nullable<decimal> grados_brix { get; set; }
        public Nullable<decimal> cantidad_bulto { get; set; }
        public string observacion { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual persona persona1 { get; set; }
        public virtual persona persona2 { get; set; }
        public virtual producto producto1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
